"""add payment_attempts and outbox

Revision ID: 4afed6a0a16a
Revises: 44e38f834cb6
Create Date: 2026-01-11 19:48:48.289416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4afed6a0a16a'
down_revision: Union[str, None] = '44e38f834cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('payload', mysql.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_aggregate', 'outbox_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_outbox_event_type', 'outbox_events', ['event_type'], unique=False)
    op.create_index('ix_outbox_published_at', 'outbox_events', ['published_at'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('requires_action', 'succeeded', 'failed', name='payment_attempt_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=64), nullable=False),
    sa.Column('provider_event_id_last', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'idempotency_key', name='uq_invoice_idemkey'),
    sa.UniqueConstraint('provider_payment_id', name='uq_provider_payment_id')
    )
    op.create_index('ix_attempt_invoice', 'payment_attempts', ['invoice_id'], unique=False)
    op.create_index('ix_attempt_status', 'payment_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attempt_status', table_name='payment_attempts')
    op.drop_index('ix_attempt_invoice', table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index('ix_outbox_published_at', table_name='outbox_events')
    op.drop_index('ix_outbox_event_type', table_name='outbox_events')
    op.drop_index('ix_outbox_aggregate', table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
